package common

type Language struct {
	AuthorizationFailed                     string
	ConnectedFailed                         string
	ConnectedSuccess                        string
	UnknownError                            string
	ErrorCode                               string
	TextDescription                         string
	ExceptionMessage                        string
	ExceptionSource                         string
	ExceptionType                           string
	ExceptionStackTrace                     string
	ExceptionTargetSite                     string
	ExceptionCustomer                       string
	SuccessText                             string
	TwoParametersLengthIsNotSame            string
	NotSupportedFunction                    string
	NotSupportedDataType                    string
	DataLengthIsNotEnough                   string
	ReceiveDataTimeout                      string
	ReceiveDataLengthTooShort               string
	MessageTip                              string
	Close                                   string
	Time                                    string
	SoftWare                                string
	BugSubmit                               string
	MailServerCenter                        string
	MailSendTail                            string
	IpAddressError                          string
	Send                                    string
	Receive                                 string
	SystemInstallOperator                   string
	SystemUpdateOperator                    string
	SocketIOException                       string
	SocketSendException                     string
	SocketHeadReceiveException              string
	SocketContentReceiveException           string
	SocketContentRemoteReceiveException     string
	SocketAcceptCallbackException           string
	SocketReAcceptCallbackException         string
	SocketSendAsyncException                string
	SocketEndSendException                  string
	SocketReceiveException                  string
	SocketEndReceiveException               string
	SocketRemoteCloseException              string
	FileDownloadSuccess                     string
	FileDownloadFailed                      string
	FileUploadFailed                        string
	FileUploadSuccess                       string
	FileDeleteFailed                        string
	FileDeleteSuccess                       string
	FileReceiveFailed                       string
	FileNotExist                            string
	FileSaveFailed                          string
	FileLoadFailed                          string
	FileSendClientFailed                    string
	FileWriteToNetFailed                    string
	FileReadFromNetFailed                   string
	FilePathCreateFailed                    string
	FileRemoteNotExist                      string
	TokenCheckFailed                        string
	TokenCheckTimeout                       string
	CommandHeadCodeCheckFailed              string
	CommandLengthCheckFailed                string
	NetClientAliasFailed                    string
	NetEngineStart                          string
	NetEngineClose                          string
	NetClientOnline                         string
	NetClientOffline                        string
	NetClientBreak                          string
	NetClientFull                           string
	NetClientLoginFailed                    string
	NetHeartCheckFailed                     string
	NetHeartCheckTimeout                    string
	DataSourceFormatError                   string
	ServerFileCheckFailed                   string
	ClientOnlineInfo                        string
	ClientOfflineInfo                       string
	ClientDisableLogin                      string
	ReConnectServerSuccess                  string
	ReConnectServerAfterTenSeconds          string
	KeyIsNotAllowedNull                     string
	KeyIsExistAlready                       string
	KeyIsNotExist                           string
	ConnectingServer                        string
	ConnectFailedAndWait                    string
	AttemptConnectServer                    string
	ConnectServerSuccess                    string
	GetClientIpaddressFailed                string
	ConnectionIsNotAvailable                string
	DeviceCurrentIsLoginRepeat              string
	DeviceCurrentIsLoginForbidden           string
	PasswordCheckFailed                     string
	DataTransformError                      string
	RemoteClosedConnection                  string
	LogNetDebug                             string
	LogNetInfo                              string
	LogNetWarn                              string
	LogNetError                             string
	LogNetFatal                             string
	LogNetAbandon                           string
	LogNetAll                               string
	AllenBradley04                          string
	AllenBradley05                          string
	AllenBradley06                          string
	AllenBradley0A                          string
	AllenBradley13                          string
	AllenBradley1C                          string
	AllenBradley1E                          string
	AllenBradley26                          string
	AllenBradleySessionStatus00             string
	AllenBradleySessionStatus01             string
	AllenBradleySessionStatus02             string
	AllenBradleySessionStatus03             string
	AllenBradleySessionStatus64             string
	AllenBradleySessionStatus65             string
	AllenBradleySessionStatus69             string
	ModbusTcpFunctionCodeNotSupport         string
	ModbusTcpFunctionCodeOverBound          string
	ModbusTcpFunctionCodeQuantityOver       string
	ModbusTcpFunctionCodeReadWriteException string
	ModbusTcpReadCoilException              string
	ModbusTcpWriteCoilException             string
	ModbusTcpReadRegisterException          string
	ModbusTcpWriteRegisterException         string
	ModbusAddressMustMoreThanOne            string
	ModbusAsciiFormatCheckFailed            string
	ModbusCRCCheckFailed                    string
	ModbusLRCCheckFailed                    string
	ModbusMatchFailed                       string
	ModbusBitIndexOverstep                  string
}

func NewLanguage() *Language {
	return &Language{
		AuthorizationFailed:          "系统授权失败，需要使用激活码授权，谢谢支持。",
		ConnectedFailed:              "连接失败：",
		ConnectedSuccess:             "连接成功！",
		UnknownError:                 "未知错误",
		ErrorCode:                    "错误代号：",
		TextDescription:              "文本描述：",
		ExceptionMessage:             "错误信息：",
		ExceptionSource:              "错误源：",
		ExceptionType:                "错误类型：",
		ExceptionStackTrace:          "错误堆栈：",
		ExceptionTargetSite:          "错误方法：",
		ExceptionCustomer:            "用户自定义方法出错：",
		SuccessText:                  "成功",
		TwoParametersLengthIsNotSame: "两个参数的个数不一致",
		NotSupportedFunction:         "当前的功能逻辑不支持",
		NotSupportedDataType:         "输入的类型不支持，请重新输入",
		DataLengthIsNotEnough:        "接收的数据长度不足，应该值:{0},实际值:{1}",
		ReceiveDataTimeout:           "接收数据超时：",
		ReceiveDataLengthTooShort:    "接收的数据长度太短：",
		MessageTip:                   "消息提示：",
		Close:                        "关闭",
		Time:                         "时间：",
		SoftWare:                     "软件：",
		BugSubmit:                    "Bug提交",
		MailServerCenter:             "邮件发送系统",
		MailSendTail:                 "邮件服务系统自动发出，请勿回复！",
		IpAddressError:               "Ip地址输入异常，格式不正确",
		Send:                         "发送",
		Receive:                      "接收",
		// 系统相关的错误信息
		SystemInstallOperator: "安装新系统：IP为",
		SystemUpdateOperator:  "更新新系统：IP为",
		// 套接字相关的信息描述
		SocketIOException:                   "套接字传送数据异常：",
		SocketSendException:                 "同步数据发送异常：",
		SocketHeadReceiveException:          "指令头接收异常：",
		SocketContentReceiveException:       "内容数据接收异常：",
		SocketContentRemoteReceiveException: "对方内容数据接收异常：",
		SocketAcceptCallbackException:       "异步接受传入的连接尝试",
		SocketReAcceptCallbackException:     "重新异步接受传入的连接尝试",
		SocketSendAsyncException:            "异步数据发送出错:",
		SocketEndSendException:              "异步数据结束挂起发送出错",
		SocketReceiveException:              "异步数据发送出错:",
		SocketEndReceiveException:           "异步数据结束接收指令头出错",
		SocketRemoteCloseException:          "远程主机强迫关闭了一个现有的连接",
		// 文件相关的信息
		FileDownloadSuccess:   "文件下载成功",
		FileDownloadFailed:    "文件下载异常",
		FileUploadFailed:      "文件上传异常",
		FileUploadSuccess:     "文件上传成功",
		FileDeleteFailed:      "文件删除异常",
		FileDeleteSuccess:     "文件删除成功",
		FileReceiveFailed:     "确认文件接收异常",
		FileNotExist:          "文件不存在",
		FileSaveFailed:        "文件存储失败",
		FileLoadFailed:        "文件加载失败",
		FileSendClientFailed:  "文件发送的时候发生了异常",
		FileWriteToNetFailed:  "文件写入网络异常",
		FileReadFromNetFailed: "从网络读取文件异常",
		FilePathCreateFailed:  "文件夹路径创建失败：",
		FileRemoteNotExist:    "对方文件不存在，无法接收！",
		// 服务器的引擎相关数据
		TokenCheckFailed:           "接收验证令牌不一致",
		TokenCheckTimeout:          "接收验证超时:",
		CommandHeadCodeCheckFailed: "命令头校验失败",
		CommandLengthCheckFailed:   "命令长度检查失败",
		NetClientAliasFailed:       "客户端的别名接收失败：",
		NetEngineStart:             "启动引擎",
		NetEngineClose:             "关闭引擎",
		NetClientOnline:            "上线",
		NetClientOffline:           "下线",
		NetClientBreak:             "异常掉线",
		NetClientFull:              "服务器承载上限，收到超出的请求连接。",
		NetClientLoginFailed:       "客户端登录中错误：",
		NetHeartCheckFailed:        "心跳验证异常：",
		NetHeartCheckTimeout:       "心跳验证超时，强制下线：",
		DataSourceFormatError:      "数据源格式不正确",
		ServerFileCheckFailed:      "服务器确认文件失败，请重新上传",
		ClientOnlineInfo:           "客户端 [ {0} ] 上线",
		ClientOfflineInfo:          "客户端 [ {0} ] 下线",
		ClientDisableLogin:         "客户端 [ {0} ] 不被信任，禁止登录",
		// Client 相关
		ReConnectServerSuccess:         "重连服务器成功",
		ReConnectServerAfterTenSeconds: "在10秒后重新连接服务器",
		KeyIsNotAllowedNull:            "关键字不允许为空",
		KeyIsExistAlready:              "当前的关键字已经存在",
		KeyIsNotExist:                  "当前订阅的关键字不存在",
		ConnectingServer:               "正在连接服务器...",
		ConnectFailedAndWait:           "连接断开，等待{0}秒后重新连接",
		AttemptConnectServer:           "正在尝试第{0}次连接服务器",
		ConnectServerSuccess:           "连接服务器成功",
		GetClientIpaddressFailed:       "客户端IP地址获取失败",
		ConnectionIsNotAvailable:       "当前的连接不可用",
		DeviceCurrentIsLoginRepeat:     "当前设备的id重复登录",
		DeviceCurrentIsLoginForbidden:  "当前设备的id禁止登录",
		PasswordCheckFailed:            "密码验证失败",
		DataTransformError:             "数据转换失败，源数据：",
		RemoteClosedConnection:         "远程关闭了连接",
		// 日志相关
		LogNetDebug:   "调试",
		LogNetInfo:    "信息",
		LogNetWarn:    "警告",
		LogNetError:   "错误",
		LogNetFatal:   "致命",
		LogNetAbandon: "放弃",
		LogNetAll:     "全部",
		// AB PLC 相关
		AllenBradley04:              "它没有正确生成或匹配标记不存在。",
		AllenBradley05:              "引用的特定项（通常是实例）无法找到。",
		AllenBradley06:              "请求的数据量不适合响应缓冲区。 发生了部分数据传输。",
		AllenBradley0A:              "尝试处理其中一个属性时发生错误。",
		AllenBradley13:              "命令中没有提供足够的命令数据/参数来执行所请求的服务。",
		AllenBradley1C:              "与属性计数相比，提供的属性数量不足。",
		AllenBradley1E:              "此服务中的服务请求出错。",
		AllenBradley26:              "IOI字长与处理的IOI数量不匹配。",
		AllenBradleySessionStatus00: "成功",
		AllenBradleySessionStatus01: "发件人发出无效或不受支持的封装命令。",
		AllenBradleySessionStatus02: "接收器中的内存资源不足以处理命令。 这不是一个应用程序错误。 相反，只有在封装层无法获得所需内存资源的情况下才会导致此问题。",
		AllenBradleySessionStatus03: "封装消息的数据部分中的数据形成不良或不正确。",
		AllenBradleySessionStatus64: "向目标发送封装消息时，始发者使用了无效的会话句柄。",
		AllenBradleySessionStatus65: "目标收到一个无效长度的信息。",
		AllenBradleySessionStatus69: "不支持的封装协议修订。",
		// Modbus相关
		ModbusTcpFunctionCodeNotSupport:         "不支持的功能码",
		ModbusTcpFunctionCodeOverBound:          "读取的数据越界",
		ModbusTcpFunctionCodeQuantityOver:       "读取长度超过最大值",
		ModbusTcpFunctionCodeReadWriteException: "读写异常",
		ModbusTcpReadCoilException:              "读取线圈异常",
		ModbusTcpWriteCoilException:             "写入线圈异常",
		ModbusTcpReadRegisterException:          "读取寄存器异常",
		ModbusTcpWriteRegisterException:         "写入寄存器异常",
		ModbusAddressMustMoreThanOne:            "地址值在起始地址为1的情况下，必须大于1",
		ModbusAsciiFormatCheckFailed:            "Modbus的ascii指令检查失败，不是modbus-ascii报文",
		ModbusCRCCheckFailed:                    "Modbus的CRC校验检查失败",
		ModbusLRCCheckFailed:                    "Modbus的LRC校验检查失败",
		ModbusMatchFailed:                       "不是标准的modbus协议",
		ModbusBitIndexOverstep:                  "位访问的索引越界，应该在0-15之间",
	}
}

var StringResources = NewLanguage()
